name: David-Gerber
favicon: null
layout_spectrum: 0.7258186091203243
typography_spectrum: 0.0644880780018866
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5119825210422277
  lightness: 0.3947104853577912
  saturation: 0.4793495985213667
  rhythmicContrast: 0.08256208547390997
purpose: []
